name: Blob storage website CI

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'
        - '.github/workflows/**'
        - 'backend/**'
    pull_request:
        branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.36.0
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        inlineScript: |
            az storage blob upload-batch --account-name htmlresume -d '$web' -s frontend/ --overwrite=true
    - name: Purge CDN endpoint
      uses: azure/CLI@v1 
      with:
        azcliversion: 2.36.0
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name htmlresume --name hariresume --resource-group Cloud_Html_Resume
  # Azure logout 
    - name: logout
      run: |
            az logout       