name: Blob storage website CI

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'
    pull_request:
        branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --subscription "4dfde764-8871-4fb4-8fce-5cf045558bcf” --account-name htmlresume -d '$web' -s frontend/ 
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --subscription "4dfde764-8871-4fb4-8fce-5cf045558bcf” --profile-name htmlresume --name htmlresume --resource-group Cloud_Html_Resume
  # Azure logout 
    - name: logout
      run: |
            az logout       